# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4 test

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "testing/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: coveralls token
          command: "echo repo_token: $COVERALLS_REPO_TOKEN > .coveralls.yml"
          working_directory: ~/project/testing

      - run:
          name: yarn install
          command: yarn install
          working_directory: ~/project/testing

      - save_cache:
          paths:
            - ~/project/testing/node_modules
          key: v1-dependencies-{{ checksum "testing/package.json" }}

      # run tests!
      - run:
          name: yarn coverage
          command: yarn coverage
          working_directory: ~/project/testing

      - run:
          name: coveralls
          command: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
          working_directory: ~/project/testing
